name = "naeos-docs"
account_id = "31ddf36d0d0fdfb04cb4f88dbcf3909f"
pages_build_output_dir = "site/public"

# Build configuration
[build]
command = "cd site && hugo --minify"
cwd = "."

# Environment variables
[env.production]
vars = { HUGO_VERSION = "0.145.0", HUGO_EXTENDED = "true", HUGO_ENV = "production" }
