package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"github.com/NAEOS-foundation/naeos/internal/generation/adapters"
	"github.com/NAEOS-foundation/naeos/internal/neir/model/language"
)

func newScaffoldCommand() *cobra.Command {
	var name, output string
	var languages []string

	cmd := &cobra.Command{
		Use:   "scaffold",
		Short: "Generate a starter project scaffold",
		Long: `Generate a starter project scaffold with all necessary files.

Example:
  naeos scaffold --name my-app
  naeos scaffold --name my-app --output ./my-app --language typescript
  naeos scaffold --name my-app --language go --language python`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if name == "" {
				return fmt.Errorf("missing required --name")
			}
			if output == "" {
				output = name
			}

			if err := os.MkdirAll(output, 0o755); err != nil {
				return fmt.Errorf("create scaffold dir: %w", err)
			}

			targetLangs := resolveScaffoldLanguages(languages)

			for _, lang := range targetLangs {
				adapter, ok := adapters.Get(lang)
				if !ok {
					continue
				}
				artifacts := adapter.GenerateProject(name)
				artifacts = append(artifacts, adapter.GenerateDockerfile(name)...)
				artifacts = append(artifacts, adapter.GenerateCI(name)...)

				for _, a := range artifacts {
					if err := writeFileInDir(output, a.Path, string(a.Content)); err != nil {
						return err
					}
				}

				coreArtifacts := adapter.GenerateModule("core", "./internal/core", name)
				for _, a := range coreArtifacts {
					if err := writeFileInDir(output, a.Path, string(a.Content)); err != nil {
						return err
					}
				}

				extraModuleFiles := map[string]string{
					"internal/core/README.md":   "# core\n\nStarter module generated by NAEOS.\n",
					"internal/core/package.go":  "package core\n\n// core module placeholder.\n",
					"internal/core/config.yaml": "name: core\nmodule: core\n",
				}
				for fileName, content := range extraModuleFiles {
					if err := writeFileInDir(output, fileName, content); err != nil {
						return err
					}
				}
			}

			readme := fmt.Sprintf("# %s\n\nGenerated by NAEOS scaffold.\n\n## Quick start\n\n- Review spec.yaml\n- Run the project\n", name)
			spec := fmt.Sprintf("project: %s\nmodules:\n  - name: core\n    path: ./internal/core\nservices:\n  - name: api\n    kind: http\n    port: 8080\n", name)
			makefile := fmt.Sprintf(".PHONY: help\n\nhelp:\n\t@echo 'Available targets:'\n\t@echo '  make help'\n\t@echo '  make scaffold'\n\nscaffold:\n\t@echo 'Scaffold complete for %s'\n", name)
			gitignore := "# Build artifacts\n/bin/\n/out/\n*.log\n"

			baseFiles := map[string]string{
				"README.md":  readme,
				"spec.yaml":  spec,
				"Makefile":   makefile,
				".gitignore": gitignore,
				"config.yaml": fmt.Sprintf("port: 8080\n"),
				"config.json": "{\"port\": 8080}\n",
			}

			for fileName, content := range baseFiles {
				if err := writeFileInDir(output, fileName, content); err != nil {
					return err
				}
			}

			_, err := fmt.Fprintf(cmd.OutOrStdout(), "scaffolded %s for %s\n", output, strings.Join(targetLangNames(targetLangs), ", "))
			return err
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "project name for the scaffold")
	cmd.Flags().StringVar(&output, "output", "", "directory where scaffold files will be created")
	cmd.Flags().StringArrayVar(&languages, "language", nil, "target language for code generation (go, typescript, python, java, rust)")
	return cmd
}

func resolveScaffoldLanguages(languages []string) []language.Language {
	if len(languages) == 0 {
		return []language.Language{language.LanguageGo}
	}
	var langs []language.Language
	for _, l := range languages {
		langs = append(langs, language.Language(l))
	}
	return langs
}

func targetLangNames(langs []language.Language) []string {
	var names []string
	for _, l := range langs {
		names = append(names, string(l))
	}
	return names
}
